apiVersion: v1
kind: Service
metadata:
  name: comtrya-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: comtrya-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
