/**
 * HTTP transport for op invocations generated by `comtrya-wit-codegen`.
 *
 * Generated TS clients import `{ invokeOp, OpResult }` from this module
 * (or its re-export `@comtrya/sdk-core`). The shape is intentionally
 * minimal: a single fetch to the kernel's GraphQL surface keyed by the
 * dotted route the codegen emits.
 */

export type OpResult<T> =
  | { ok: true; value: T }
  | {
      ok: false;
      error: {
        code:
          | "not-found"
          | "conflict"
          | "forbidden"
          | "unauthenticated"
          | "bad-input"
          | "internal"
          | "unavailable";
        message: string;
        path?: string;
      };
    };

export interface InvokeOpOptions {
  /** Override the kernel base URL (defaults to same-origin). */
  baseUrl?: string;
  /** Abort signal for cancellation. */
  signal?: AbortSignal;
  /** Optional bearer token; otherwise the cookie session is used. */
  token?: string;
}

/**
 * Send an op invocation to the kernel. The kernel routes by extension id +
 * interface + op name, validates the JSON payload against the target's
 * WIT-declared input schema, and returns either `{ok: true, value}` or
 * `{ok: false, error}`.
 */
export async function invokeOp<T = unknown>(
  extensionId: string,
  interfaceName: string,
  opName: string,
  input?: unknown,
  options: InvokeOpOptions = {},
): Promise<OpResult<T>> {
  const baseUrl = options.baseUrl ?? "";
  const url = `${baseUrl}/api/ops/${encodeURIComponent(
    extensionId,
  )}/${encodeURIComponent(interfaceName)}/${encodeURIComponent(opName)}`;
  const headers: Record<string, string> = {
    "content-type": "application/json",
  };
  if (options.token) headers["authorization"] = `Bearer ${options.token}`;
  try {
    const response = await fetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(input ?? null),
      signal: options.signal,
      credentials: "include",
    });
    const text = await response.text();
    if (!response.ok) {
      let parsed: Record<string, unknown> | undefined;
      try {
        parsed = text ? JSON.parse(text) : undefined;
      } catch {
        parsed = undefined;
      }
      const errCode = mapStatusToErrorCode(response.status);
      return {
        ok: false,
        error: {
          code: (parsed?.code as OpResult<unknown> extends { ok: false }
            ? never
            : never) ??
            errCode,
          message:
            (parsed?.message as string | undefined) ??
            text ||
            response.statusText,
          path: parsed?.path as string | undefined,
        },
      };
    }
    return { ok: true, value: text ? JSON.parse(text) : null } as OpResult<T>;
  } catch (err) {
    return {
      ok: false,
      error: {
        code: "unavailable",
        message: err instanceof Error ? err.message : String(err),
      },
    };
  }
}

function mapStatusToErrorCode(status: number): OpResult<unknown> extends {
  ok: false;
}
  ? never
  : never;
function mapStatusToErrorCode(
  status: number,
):
  | "not-found"
  | "conflict"
  | "forbidden"
  | "unauthenticated"
  | "bad-input"
  | "internal"
  | "unavailable" {
  switch (status) {
    case 400:
      return "bad-input";
    case 401:
      return "unauthenticated";
    case 403:
      return "forbidden";
    case 404:
      return "not-found";
    case 409:
      return "conflict";
    case 503:
      return "unavailable";
    default:
      return "internal";
  }
}
