[package]
name = "comtrya-server"
version.workspace = true
edition.workspace = true

[dependencies]
axum = "0.7.9"
comtrya-core = { path = "../core" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
tokio = { version = "1.52.1", features = ["macros", "net", "rt-multi-thread"] }
wasmtime = { version = "43.0.2", default-features = false, features = ["anyhow", "component-model", "cranelift", "runtime", "std", "wat"] }
